### PR TITLE
Made issue templates

### PR DESCRIPTION
**Pull request by elichai**
This will help users and us to create sensible features/bug reports.

### CODE REVIEW

**Review by lacabra — APPROVED** [review]
Looks good to me.

Merging onto `develop` first, to `master` later.

**Comment by elichai** [comment]
ok. just FYI this won't take into effect unless it's in the default branch

**Comment by lacabra** [comment]
Understood, thanks for clarifying.

FYI, your commit was not signed.

**Comment by elichai** [comment]
Yes. I didn't made this commit.
This change is through the repo settings and github automatically makes a commit. sorry for that.

**Pull request merged**
