### PR TITLE
Added the gas limit to signature checks in contract deployment and task validation

### PR DESCRIPTION
**Pull request by reuvenpo**
This PR is related to enigmampc/enigma-core#221 and (hopefully) adjusts the verification done in enigma-contract to the signing done by enigma-core/enclave.

@apalepu23 Please review this PR and check that i indeed implemented this correctly. this is my first time touching solidity in general and this repo in particular. Also, should i make similar changes to the files suffixed with `*Simulation`?

### CODE REVIEW

**Comment by reuvenpo** [comment]
@apalepu23 I can see that the CI is failing because the gasLimit is a uint256, were i expected it to be a uint64. I expected that because that's how it is in enigma-core, and because the usedGas is a uint64. I think that we should probably update all these to be u256 as that's what someone used to ethereum would expect, but i don't know the system well enough yet. what do you think about this? should i just convert to uint64, or should be revisit the rest of the code to use uint256s?

https://travis-ci.org/enigmampc/enigma-contract/builds/586495679?utm_source=github_status&utm_medium=notification

**Comment by apalepu23** [comment]
Hey @reuvenpo ! This looks good to me, and the addition is useful. Couple of comments...you're right, core is definitely outputting `uint64` for `gasUsed`. I think for consistency's sake, makes sense to have `gasUsed` and a task's `gasLimit` to be of the same type. `uint256` is only what "someone would expect" insofar as it's the default (`uint` = `uint256`), however if there is a smaller storage type that can be used, we definitely should. So adjusting the gasLimit attribute in the task struct definition to `uint64` makes sense to me. Feel free to edit that accordingly, or let me know if you need any assistance in that!

**Comment by reuvenpo** [comment]
I'll play around with it on Sunday morning when I'm back at the office, but I think that the real question here is a question of use cases. Are people likely to want more that 2^64 gas limit for a task? Well, maybe, depending on the price of gas and the amount of gas units consumed by an average task. Neither of these parameters are known to me, but in any case, I understand that solidity does not protect from integer overflows/underflows, so it's definitely something we want to get right. Obviously, u256 is a safe choice, but I'm not qualified to argue about the optimization you propose.

**Comment by reuvenpo** [comment]
Alright, so after discussing this earlier with Moria and Guy, we decided to go ahead and use u64 for these fields. I made a few minimal changes to the solidity code that hopefully covers this on the contract side, but we will probably need to update the code that calls the secret contract too, right?

I tried looking for references to the names of functions that I changed, but I only found them in minified js files. If we autogenerate the enigma js bindings, why do we store them in the source code? We can save a lot of storage by removing these files and then ignoring them.

**Comment by reuvenpo** [comment]
https://github.com/enigmampc/enigma-contract/pull/152

**Pull request closed without merging**
