### PR TITLE
Fix #75

### LINKED ISSUE #75: Execution of erc20 contract runs out of gas
After @AvishaiW fixing [115](https://github.com/enigmampc/enigma-core/issues/115) in `core`, I adjusted the integrationTest to execute a secret computation on the erc20 contract [here](https://github.com/enigmampc/enigma-contract/blob/develop/enigma-js/test/integrationTests/template.10_execute_erc20.js), but the test fails because `core` reports running out of gas:
```
Error in execution of smart contract function: Invocation resulted in gas limit violated
```
As reported in [117](https://github.com/enigmampc/enigma-core/issues/117) in `core`, it is not an out-of-gas per se (and the gas limit is set to 10M, which is more than enough to run that computation), but a mismatch in the parameters that are passed to the computation. Thus, I would appreciate if @AvishaiW could troubleshoot this issue.

The order of integration tests to run to troubleshoot this issue are as follows:
```
01_init.spec.js
02_deploy_erc20.spec.js
10_execute_erc20.spec.js
```

### PR DESCRIPTION
**Pull request by lacabra**
As discussed offline wiht @AvishaiW, the client now uses 32-byte addresses instead of the standard Ethereum 20-bytes. Still I'm getting `Unreachable` and the integrationTest don't pass, so this is WIP

### CODE REVIEW

**Comment by AvishaiW** [comment]
@lacabra I looked into this and noticed there is still a confusion of the addresses given to the contract in the deployment-it should send 32bit addresses the same as in the execution.
furthermore, it's possible that the signing function used on both ends are not similar and thus returning an error, however, this needs to be checked if the first bug didn't fix the issue.

**Comment by AvishaiW** [comment]
after looking a bit more into it, it seems the signing function is similar, however, I'm trying to figure out if it matters that the output of the function `EthCrypto.sign` is a string or a bytes array, and if it's a string, do you convert it anywhere to bytes?

**Comment by lacabra** [comment]
You are raising a good point @AvishaiW. The output of `EthCrypto.sign()` is the hex string representation, as documented here: https://github.com/pubkey/eth-crypto#sign, analogous to how the `bytes32` addresses that I'm passing are also hex strings at that early point in the code. 

All these params are later processed by `abi.encodeParameters()` [here](https://github.com/enigmampc/enigma-contract/blob/3048db58f1ccc0fe133e168f0e64e62b7322ce65/enigma-js/src/Enigma.js#L103) and then converted into bytes [here](https://github.com/enigmampc/enigma-contract/blob/3048db58f1ccc0fe133e168f0e64e62b7322ce65/enigma-js/src/Enigma.js#L106) and then encrypted [here](https://github.com/enigmampc/enigma-contract/blob/3048db58f1ccc0fe133e168f0e64e62b7322ce65/enigma-js/src/Enigma.js#L153). This chain of functions are ordered this way so that the outputs of one match the inputs of the next, and match what `core` expects (as we reviewed this with Moria some days ago).

I suggest you log what `core` gets as inputs from this call to `mint()`, and let me know if any of the types needs adjustment, because I'm coding the way it is to maintain consistency with what I have seen earlier that `core` expects.

**Comment by AvishaiW** [comment]
Hey @lacabra, After running many tests, I noticed 2 bugs:
1. This ERC20 contract is meant to run on a hypothetical Enigma protocol in which the addresses are 32 bytes long and are a hash of the public key of the user's key pair. `address = userPubKey.keccak256()`
This needs to be changed both in the deployment and the execution and it's not enough to add zero's to an existing Ethereum address.

2. you don't send the inputs as an array into the [hash function](https://github.com/enigmampc/enigma-contract/blob/integration/enigma-js/test/integrationTests/template.10_execute_erc20.js#L57) leading to an incorrect message which leads to an error in the contract.

after adding a temp fix for the first bug and fixing the second, the execution passed on core, but seems that you haven't finished writing the actual test leading to a fail.

**Comment by lacabra** [comment]
Hey @AvishaiW, in response to your comments above:

1. I'm aware of the `bytes32` requirements for the addresses passed as arguments to the secret contract, and they were already implemented in the `compute` test. From the link that you posted above, you may have been looking at the wrong branch, since you linked to `develop` instead of the branch of this PR `fixerc20`. However, I noticed that the deploy test was missing the `bytes32` treatment, and that has just been added in commit 27402c7 above.

2. I disagree with your assessment of the input parameters to the hash function. What you refer to may be the way it is implemented in Rust, but that's not the case how it is implemented in Javascript. As you can see [here](https://github.com/enigmampc/enigma-contract/blob/e7284d1d2068cab55c71e914a4efa5431dfbdd2a/enigma-js/src/enigma-utils.js#L196), we are using `web3Utils.soliditySha3()` for hashing, which as documented [here](https://web3js.readthedocs.io/en/1.0/web3-utils.html#soliditysha3) takes a hexString and interprets it as the `bytes` array that you refer to.

We may need to review this together to get to the bottom of it, I feel we are very close!

**Comment by lacabra** [comment]
I had misunderstood your second point above. You were correct in your assessment, and once I sent it as an array in 27402c7, the compute works! 

Thank you

**Review by apalepu23 — APPROVED** [review]

**Pull request merged**
